### ISSUE TITLE
Re-deployment needed after appspot Go1.9 depreprecation

### ISSUE THREAD

**Issue by ALTree** [zorion/go-tour-ca#1]
Hi there,

this Go tour translation is currently offline due to the appspot deprecation of Go1.9:

```
Go 1.9 is no longer available.
Please refer to https://goo.gl/aESk5L for more information.
```

As documented in the linked page:

> To continue running your apps, migrate them to the Go 1.11 standard
  runtime or newer runtimes.

A re-deployment is needed to bring the translation back online.

**Comment by zorion** [comment]
Thanks for your report.
I'm busy currently adapting the new version a new branch but I don't have time for it.
I was developing it in beta-dot-go-tour-ca.appspot.com, but since go-tour-ca.appspot.com is not working at all I will move it to master and to go-tour-ca.appspot.com, it will be better something that nothing, I guess.
